name: model-swecha
on: [push]
jobs:
        run:
                runs-on: [ubuntu-latest]
                container: docker://dvcorg/cml-py3:latest
                steps:
                        - uses: actions/checkout@v2
                        - name: cml_run
                          env:
                                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                          run: |

                                  # ML workflow goes here
                                  dvc pull data
                                  pip install -r requirements.txt
                                  dvc repro
                                  dvc metrics show --show-md >> report.md
                                  echo >> report.md
                                  cml-send-comment report.md

